export DOTFILES="$HOME/dotfiles"
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE=true
DISABLE_MAGIC_FUNCTIONS=true
ENABLE_CORRECTION=false

plugins=(git)

source $ZSH/oh-my-zsh.sh

for file in paths exports aliases functions herd; do
  source "$DOTFILES/zsh/$file.zsh"
done

[[ -f ~/.zsh/conda.zsh ]] && source ~/.zsh/conda.zsh
